### ISSUE TITLE
Times out in Github Action

### ISSUE THREAD

**Issue by benjheath0** [bahmutov/start-server-and-test#287]
# Bug Report
I am running version `1.11.6`. My server is nodejs, rendering server side EJS templates. I am using Nightwatch for tests. My scripts are:
`ci: start-server-and-test start http-get://localhost:8080 test:e2e`
`start: node server.js`
`"test:e2e": "nightwatch --env default --headless"`

Running `npm run ci` works perfectly locally, but when I run in a Github Action pipeline it is timing out. As you can see, I am logging a confirmation that our express server is up and running. I am getting the following error.

```
> start-server-and-test start http-get://localhost:8080 test:e2e

1: starting server using command "npm run start"
and when url "[ 'http-get://localhost:8080' ]" is responding with HTTP status code 200
running tests using command "npm run test:e2e"


> project@1.0.0 start /home/runner/work/project/project
> node server.js

Express server listening on port 8080
Error: Timed out waiting for: http://localhost:8080
    at MergeMapSubscriber.project (/home/runner/work/project/project/node_modules/wait-on/lib/wait-on.js:130:25)
    at MergeMapSubscriber._tryNext (/home/runner/work/project/project/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/home/runner/work/project/project/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/home/runner/work/project/project/node_modules/rxjs/internal/Subscriber.js:66:18)
    at AsyncAction.dispatch [as work] (/home/runner/work/project/project/node_modules/rxjs/internal/observable/timer.js:31:16)
    at AsyncAction._execute (/home/runner/work/project/project/node_modules/rxjs/internal/scheduler/AsyncAction.js:71:18)
    at AsyncAction.execute (/home/runner/work/project/project/node_modules/rxjs/internal/scheduler/AsyncAction.js:59:26)
    at AsyncScheduler.flush (/home/runner/work/project/project/node_modules/rxjs/internal/scheduler/AsyncScheduler.js:52:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tfiiu@1.0.0 ci: `start-server-and-test start http-get://localhost:8080 test:e2e`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tfiiu@1.0.0 ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-11-20T16_38_11_687Z-debug.log
```

**Comment by bahmutov** [comment]
Can you enable https://github.com/bahmutov/start-server-and-test#debugging and paste the debug log during pinging the server?

**Comment by benjheath0** [comment]
Here is my log. Again though, this works perfectly fine locally.

```
 project@1.0.0 ci /home/runner/work/project/project
> start-server-and-test start http://localhost:8080 test:e2e

2020-11-20T17:33:47.352Z start-server-and-test parsing CLI arguments: [ 'start', 'http://localhost:8080', 'test:e2e' ]
2020-11-20T17:33:47.354Z start-server-and-test parsed args: { services: [ { start: 'npm run start', url: [Array] } ], test: 'npm run test:e2e' }
1: starting server using command "npm run start"
and when url "[ 'http://localhost:8080' ]" is responding with HTTP status code 200
running tests using command "npm run test:e2e"

2020-11-20T17:33:47.355Z start-server-and-test single service "npm run start" to run and test
2020-11-20T17:33:47.356Z start-server-and-test starting server with command "npm run start", verbose mode? true
2020-11-20T17:33:47.363Z start-server-and-test starting waitOn [ 'http://localhost:8080' ]
2020-11-20T17:33:47.364Z start-server-and-test wait-on options { resources: [ 'http://localhost:8080' ], interval: 2000, window: 1000, timeout: 300000, verbose: true, strictSSL: true, log: true }
waiting for 1 resources: http://localhost:8080
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: connect ECONNREFUSED 127.0.0.1:8080

> tfiiu@1.0.0 start /home/runner/work/TheFightIsInUs/TheFightIsInUs
> node server.js

true string false
Express server listening on port 8080
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500
making HTTP(S) head request to  url:http://localhost:8080 ...

**Comment by Marsunpaisti** [comment]
Im having a similar issue in Gitlab ci. Works locally but not in pipeline, even though server is definitely up its not getting past the check

**Comment by bahmutov** [comment]
From the debug log I see 500 server error, why would that happen?

making HTTP(S) head request to  url:http://localhost:8080 ...
  HTTP(S) error for http://localhost:8080 Error: Request failed with status code 500

**Comment by Marsunpaisti** [comment]
Im just getting this on repeat with debug output on...
`making HTTP(S) head request to  url:http://localhost:8081/ ...
  HTTP(S) error for http://localhost:8081/ Error: connect ECONNREFUSED 127.0.0.1:8081`

However localhost:8081 should be responding, just not doing it for the script for some reason

**Comment by edward-morgan-avalara** [comment]
Any movement on this? I'm having a similar issue with Gitlab pipeline:

```> start-server-and-test start http-get://172.17.0.3:3000 cy:run
2021-01-08T21:54:28.774Z start-server-and-test parsing CLI arguments: [ 'start', 'http-get://172.17.0.3:3000', 'cy:run' ]
2021-01-08T21:54:28.776Z start-server-and-test parsed args: { services: [ { start: 'npm run start', url: [Array] } ], test: 'npm run cy:run' }
1: starting server using command "npm run start"
and when url "[ 'http-get://172.17.0.3:3000' ]" is responding with HTTP status code 200
running tests using command "npm run cy:run"
2021-01-08T21:54:28.778Z start-server-and-test single service "npm run start" to run and test
2021-01-08T21:54:28.779Z start-server-and-test starting server with command "npm run start", verbose mode? true
2021-01-08T21:54:28.787Z start-server-and-test starting waitOn [ 'http-get://172.17.0.3:3000' ]
2021-01-08T21:54:28.787Z start-server-and-test wait-on options { resources: [ 'http-get://172.17.0.3:3000' ], interval: 2000, window: 1000, timeout: 300000, verbose: true, strictSSL: false, log: true }
waiting for 1 resources: http-get://172.17.0.3:3000
making HTTP(S) get request to  url:http://172.17.0.3:3000 ...
  HTTP(S) error for http://172.17.0.3:3000 Error: connect ECONNREFUSED 172.17.0.3:3000
> customer-portal-ui@0.1.0 start /builds/orl/customer-portal-ui
> react-scripts start
making HTTP(S) get request to  url:http://172.17.0.3:3000 ...
  HTTP(S) error for http://172.17.0.3:3000 Error: connect ECONNREFUSED 172.17.0.3:3000
making HTTP(S) get request to  url:http://172.17.0.3:3000 ...
  HTTP(S) error for http://172.17.0.3:3000 Error: connect ECONNREFUSED 172.17.0.3:3000
ℹ ｢wds｣: Project is running at http://172.17.0.3/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: Content not from webpack is served from /builds/orl/customer-portal-ui/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...
making HTTP(S) get request to  url:http://172.17.0.3:3000 ...
making HTTP(S) get request to  url:http://172.17.0.3:3000 ...
making HTTP(S) get request to  url:http://172.17.0.3:3000 ...```

**Comment by bahmutov** [comment]
Honestly I have not seen this error in my repos, if anyone gets blocked by this and can debug it, I would be super happy

**Comment by lleki** [comment]
I am also getting same time out and `ECONNREFUSED` error on CI when trying run my Cypress tests on Github Action. 
 It passes locally.

I found hack for it to pass on CI but I end up with two Cypresses running which is not good.

package.json scripts
```
    "start:ci": "next start -p 4000",
    "cy:run": "cypress run",
    "test:e2e:ci": "export NODE_ENV=test && start-server-and-test start:ci http://localhost:4000 cy:run",

```

first try I did 
workflow yml.
```
steps:
      - name: Checkout
        uses: actions/checkout@v2
.....
....
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run test:e2e:ci
```
it worked but I ended up with two cypress tests running, the cypress/github-action default one + my script `(npm run test:e2e:ci)`
So on second try I did
workflow yml.
```
steps:
      - name: Checkout
        uses: actions/checkout@v2
.....
....
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start:ci 
          command: npm run test:e2e:ci 
```

the use of `command` was recommended by cypress/github-action to override THEIR `cypress run` with my own test command, which would fix my two cypress tests running. But this kept failing with the timeout/ ECONNREFUSED so I tried adding the `start` in front and finally the CI works except of course then npm run start is being called twice and there is a small error for Port in use 4000

If anyone has any pointers, please let me know, I've been on this for a few days now.

**Comment by lleki** [comment]
> @lleki Did u solve it? I'm experiencing the same issue

No, so What made it tricky was the script to use start-server-test module meant we had to include start server in same as cy:run and it ended up duplicating the cypress runs for us.

Turns out Cypress Github Action has a Custom Wait-On command and I used that instead of start-server.

**Comment by alumni** [comment]
If you have any kind of response (500 in this case), most likely the issue is coming from the server itself that behaves differently on CI.

There is also an upstream issue, btw: https://github.com/jeffbski/wait-on/issues/86.

You can also try replacing `start-server-and-test start <url> test` with `concurrently` + `wait-on`:
```sh
concurrently --kill-others \
  'start' \
  'wait-on --verbose <url> && test'
```

**Comment by Leksat** [comment]
In my case this started to happen both on GitHub CI and locally after a major update of `axios`.

In my setup I was starting Drupal dev server on `127.0.0.1` with `php -S 127.0.0.1:8888 .ht.router.php`. Yet, I used `localhost` for testing: `start-server-and-test start 8888 test`.

Somehow, this worked well until the `axios` update. Then it broke:
```
making HTTP(S) head request to  url:http://localhost:8888 ...
  HTTP(S) error for http://localhost:8888 Error: connect ECONNREFUSED ::1:8888
```

To resolve it, I changed the server address from `127.0.0.1` to `localhost` (I start server with `php -S localhost:8888 .ht.router.php`). And now it works again 🎉

**Comment by abraham** [comment]
After upgrade from Node v16 to v18 I ran into the same error with my Firebase Emulator server. I had to switch from `localhost` to `127.0.0.1`.

```
start-server-and-test start:firebase http://127.0.0.1:5000/ test
```

**Comment by raylyanway** [comment]
Unfortunately, it doesn't work with CRA (create-react-app). 
To make it works, I had to downgrade to Node.js v16.19.0.

**Comment by bahmutov** [comment]
Can anyone provide a small public repo showing the problem?

**Comment by abraham** [comment]
Example repo: https://github.com/abraham/ssat
✅ on Node 16: https://github.com/abraham/ssat/actions/runs/4050710447/jobs/6968356428
🟥 on Node 18: https://github.com/abraham/ssat/actions/runs/4050710447/jobs/6968356507

**Comment by tariqulislam** [comment]
I had just solve this problem with pm2. in script section
"e2e:headless": "pm2 start 'yarn start' --name next-js-app && yarn cypress:headless && pm2 kill"

**Comment by raylyanway** [comment]
> Can anyone provide a small public repo showing the problem?

Create a new project using this: `npx create-front-end-js-stub <name-of-your-project>`

go to the project: `cd <name-of-your-project>`
and run: `npm run cy:dev`

With Node.js v.16.19.0 Cypress will run, but with v.18.13.0 not.

**Comment by sushil-truemark** [comment]
In my case,
I temporarily resolved this issue by downgrading node version to 16.xx from 18.xx.

**Comment by MikeMcC399** [comment]
@sushil-truemark 

> I temporarily resolved this issue by downgrading node version to 16.xx from 18.xx.

Node.js `16` will enter [end-of-life](https://github.com/nodejs/release#release-schedule) later this year, so it may be better to look for a solution which has a longer lifetime. You can find workarounds for the Cypress JavaScript [github-action](https://github.com/cypress-io/github-action) on

https://github.com/cypress-io/github-action#wait-on-with-nodejs-18

These are generic workarounds so they can also be used for `start-server-and-test`

It's also worth noting that the original issue from @BenjaminHeath96 is not related to the later issues caused by Node.js 18 and later.

**Comment by vishwa3** [comment]
@BenjaminHeath96 @Marsunpaisti @edward-morgan-avalara - I am also getting this error in Jenkins pipeline but working fine on local - 

Could you please let me know how to turn on debugging - I have checked [https://github.com/bahmutov/start-server-and-test#debugging](url)  but didn't get it 

In which file do I need to set DEBUG=start-server-and-test

**Comment by vishwa3** [comment]
I am also facing the same issue, locally it works fine but stops working in Jenkins pipeline - fixed it using tcp:PORT

Also using Node version 18.17.0 locally as well as on pipeline and changing versions like Node 16 didn't help so maybe its not related to Node version

Logs - 

```
[2023-10-20T23:18:59.926Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:18:59.927Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:01.868Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:02.135Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:03.803Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:04.385Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:05.795Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:06.382Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:07.794Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:08.057Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:10.012Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:10.012Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:11.952Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:11.952Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:13.892Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:14.162Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:16.103Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:16.103Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:18.045Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:18.045Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:19.998Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:19.998Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:21.937Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:22.203Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:24.153Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:24.153Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:26.107Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:26.107Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:28.122Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:28.122Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:30.069Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:30.069Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:32.007Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:32.007Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:33.953Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:34.222Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:36.160Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:36.161Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:38.100Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:38.100Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:40.041Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:40.041Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:41.988Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:42.252Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:44.208Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:44.208Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:46.148Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:46.148Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:48.118Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:48.118Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:50.154Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:50.154Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:52.098Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:52.098Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:54.037Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:54.037Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:56.000Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:56.000Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:19:57.964Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:19:58.233Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:00.218Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:00.218Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:02.215Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:02.215Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:04.162Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:04.162Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:06.099Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:06.099Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:08.035Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:08.035Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:09.970Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:10.235Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:12.176Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:12.176Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:14.112Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:14.112Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:16.051Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:16.319Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:18.254Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:18.254Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:20.190Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:20.190Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:22.125Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:22.125Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:24.063Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:24.063Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:26.003Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:26.277Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:28.226Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:28.226Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:30.171Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:30.171Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:32.105Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:32.105Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:34.048Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:34.048Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:35.991Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:36.257Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:38.216Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:38.216Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:40.151Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:40.151Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:42.094Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:42.094Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:44.246Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:44.246Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:46.085Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:46.085Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:47.909Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:48.326Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:50.486Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:50.486Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:51.906Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:52.284Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:54.062Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:54.425Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:55.930Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:56.294Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:20:58.332Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:20:58.332Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:00.325Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:00.325Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:02.330Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:02.330Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:04.318Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:04.318Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:06.264Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:06.264Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:08.260Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:08.260Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:10.281Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:10.281Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:12.351Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:12.351Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:14.293Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:14.293Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:16.234Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:16.527Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:18.018Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:18.293Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:20.270Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:20.271Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:22.210Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:22.476Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:23.882Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:24.470Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:25.893Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:26.482Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:27.895Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:28.486Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:29.942Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:30.524Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:31.927Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:32.510Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:33.924Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:34.512Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:35.920Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:36.499Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:37.906Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:38.489Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:39.897Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:40.480Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:42.415Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:42.415Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:44.356Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:44.356Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:46.295Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:46.561Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:47.966Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:48.605Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:50.046Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:50.312Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:52.253Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:52.253Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:54.228Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:54.498Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:55.918Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:56.508Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:21:57.947Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:21:58.536Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:00.010Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:00.279Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:02.272Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:02.272Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:04.216Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:04.481Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:06.421Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:06.421Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:08.361Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:08.361Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:10.297Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:10.297Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:12.270Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:12.557Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:13.968Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:14.555Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:15.965Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:16.551Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:17.957Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:18.541Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:19.945Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:20.528Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:21.937Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:22.521Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:24.461Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:24.461Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:26.404Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:26.404Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:28.342Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:28.342Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:30.289Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:30.289Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:32.234Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:32.500Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:34.437Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:34.437Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:35.968Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:36.297Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:38.321Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:38.321Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:40.261Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:40.526Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:42.469Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:42.469Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:44.408Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:44.408Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:46.352Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:46.352Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:48.372Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:48.372Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:50.308Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:50.308Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:52.248Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:52.513Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:54.451Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:54.451Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:56.430Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:56.430Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:22:58.396Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:22:58.396Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:23:00.384Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:23:00.384Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:23:02.354Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:23:02.354Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:23:04.291Z] making HTTP(S) head request to  url:http://127.0.0.1:3000/ ...

[2023-10-20T23:23:04.291Z]   HTTP(S) error for http://127.0.0.1:3000/ Error: Parse Error: Expected HTTP/

[2023-10-20T23:23:06.243Z] wait-on(1082) Timed out waiting for: http://127.0.0.1:3000/; exiting with error

[2023-10-20T23:23:06.243Z] 2023-10-20T23:23:05.719Z start-server-and-test error waiting for url [ 'http://127.0.0.1:3000/' ]

[2023-10-20T23:23:06.243Z] 2023-10-20T23:23:05.719Z start-server-and-test Timed out waiting for: http://127.0.0.1:3000/

[2023-10-20T23:23:06.243Z] 2023-10-20T23:23:05.721Z start-server-and-test getting child processes

[2023-10-20T23:23:06.243Z] 2023-10-20T23:23:05.744Z start-server-and-test stopping child processes

[2023-10-20T23:23:06.243Z] 2023-10-20T23:23:05.745Z start-server-and-test stopping server

[2023-10-20T23:23:06.243Z] 2023-10-20T23:23:05.747Z start-server-and-test getting child processes

[2023-10-20T23:23:06.243Z] Error: Timed out waiting for: http://127.0.0.1:3000/
```

**Comment by gorankarlic** [comment]
Fixed the same issue by changing the server hostname from 'localhost' to '127.0.0.1'; one possible cause is that 'localhost' resolves to different IPs if IPv4 or IPv6 is used.

**Comment by Curs3W4ll** [comment]
I'm still having this issue (but with GitLab CI).

In the CI job output, it will timed out, see output:
```
start-server-and-test 'vite preview --port 4173' http://localhost:4173/ 'cypress run --e2e'
1: starting server using command "vite preview --port 4173"
and when url "[ 'http://localhost:4173'/ ]" is responding with HTTP status code 200
running tests using command "cypress run --e2e"
[sentry-vite-plugin] Warning: No auth token provided. Will not create release. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
[sentry-vite-plugin] Warning: No auth token provided. Will not upload source maps. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
  ➜  Local:   http://localhost:4173/
  ➜  Network: use --host to expose
Error: Timed out waiting for: http://localhost:4173
    at /builds/epitech-it-2025/medali/medali-client-website/node_modules/wait-on/lib/wait-on.js:131:31
    at doInnerSub (/builds/epitech-it-2025/medali/medali-client-website/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:31)
    at outerNext (/builds/epitech-it-2025/medali/medali-client-website/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:70)
    at OperatorSubscriber._this._next (/builds/epitech-it-2025/medali/medali-client-website/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at Subscriber.next (/builds/epitech-it-2025/medali/medali-client-website/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at AsyncAction.work (/builds/epitech-it-2025/medali/medali-client-website/node_modules/rxjs/dist/cjs/internal/observable/timer.js:28:28)
    at AsyncAction._execute (/builds/epitech-it-2025/medali/medali-client-website/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:79:18)
    at AsyncAction.execute (/builds/epitech-it-2025/medali/medali-client-website/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:[67](https://gitlab.com/epitech-it-2025/medali/medali-client-website/-/jobs/7203811528#L67):26)
    at AsyncScheduler.flush (/builds/epitech-it-2025/medali/medali-client-website/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncScheduler.js:38:33)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

When I manually connect to the Docker container that run the CI job, and curl `http://localhost:4173`, it works as expected, returning HTTP 200.

I'm able to run debug steps if needed

**Comment by FloBam** [comment]
After running in the same issue in GitLab I was able to resolve the issue by setting 
```
import * as dns from 'node:dns';

dns.setDefaultResultOrder('ipv4first');
```
in my `vite.config.ts`
